// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Node struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Hostname  string     `json:"hostname"`
	Ip        string     `json:"ip"`
	Cpu       int64      `json:"cpu"`
	Memory    int64      `json:"memory"`
	Arch      string     `json:"arch"`
	Region    string     `json:"region"`
	Type      string     `json:"type"`
	Status    string     `json:"status"`
	LastSeen  time.Time  `json:"last_seen"`
	Labels    *string    `json:"labels"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type OnboardingToken struct {
	Token     string     `json:"token"`
	Used      bool       `json:"used"`
	ExpiresAt time.Time  `json:"expires_at"`
	CreatedAt *time.Time `json:"created_at"`
}
