// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package db

import (
	"context"
	"time"
)

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (
    id,
    name,
    hostname,
    ip,
    cpu,
    memory,
    arch,
    region,
    type,
    status,
    last_seen
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNodeParams struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Hostname string    `json:"hostname"`
	Ip       string    `json:"ip"`
	Cpu      int64     `json:"cpu"`
	Memory   int64     `json:"memory"`
	Arch     string    `json:"arch"`
	Region   string    `json:"region"`
	Type     string    `json:"type"`
	Status   string    `json:"status"`
	LastSeen time.Time `json:"last_seen"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.Exec(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Hostname,
		arg.Ip,
		arg.Cpu,
		arg.Memory,
		arg.Arch,
		arg.Region,
		arg.Type,
		arg.Status,
		arg.LastSeen,
	)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes
WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, hostname, ip, cpu, memory, arch, region, type, status, last_seen, labels, created_at, updated_at
FROM nodes
WHERE id = ?
`

func (q *Queries) GetNodeByID(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Ip,
		&i.Cpu,
		&i.Memory,
		&i.Arch,
		&i.Region,
		&i.Type,
		&i.Status,
		&i.LastSeen,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodes = `-- name: GetNodes :many
SELECT id, name, hostname, ip, cpu, memory, arch, region, type, status, last_seen, labels, created_at, updated_at
FROM nodes
`

func (q *Queries) GetNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, getNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Ip,
			&i.Cpu,
			&i.Memory,
			&i.Arch,
			&i.Region,
			&i.Type,
			&i.Status,
			&i.LastSeen,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeUnhealthy = `-- name: MarkNodeUnhealthy :exec
UPDATE nodes
SET status = 'unhealthy',
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkNodeUnhealthy(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markNodeUnhealthy, id)
	return err
}

const updateHeartbeat = `-- name: UpdateHeartbeat :exec
UPDATE nodes
SET last_seen = CURRENT_TIMESTAMP,
    status = 'healthy',
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateHeartbeat(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateHeartbeat, id)
	return err
}

const updateNodeIP = `-- name: UpdateNodeIP :exec
UPDATE nodes
SET ip = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNodeIPParams struct {
	Ip string `json:"ip"`
	ID string `json:"id"`
}

func (q *Queries) UpdateNodeIP(ctx context.Context, arg UpdateNodeIPParams) error {
	_, err := q.db.Exec(ctx, updateNodeIP, arg.Ip, arg.ID)
	return err
}
