// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboard.sql

package db

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO onboarding_tokens (
    token,
    expires_at
) VALUES (?, ?)
`

type CreateTokenParams struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken, arg.Token, arg.ExpiresAt)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM onboarding_tokens
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const getToken = `-- name: GetToken :one
SELECT token, used, expires_at, created_at
FROM onboarding_tokens
WHERE token = ?
`

func (q *Queries) GetToken(ctx context.Context, token string) (OnboardingToken, error) {
	row := q.db.QueryRowContext(ctx, getToken, token)
	var i OnboardingToken
	err := row.Scan(
		&i.Token,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidToken = `-- name: GetValidToken :one
SELECT token, used, expires_at, created_at
FROM onboarding_tokens
WHERE token = ?
  AND used = FALSE
  AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetValidToken(ctx context.Context, token string) (OnboardingToken, error) {
	row := q.db.QueryRowContext(ctx, getValidToken, token)
	var i OnboardingToken
	err := row.Scan(
		&i.Token,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE onboarding_tokens
SET used = TRUE
WHERE token = ?
`

func (q *Queries) MarkTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markTokenUsed, token)
	return err
}
