// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateNode(ctx context.Context, arg CreateNodeParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteNode(ctx context.Context, id string) error
	GetNodeByID(ctx context.Context, id string) (Node, error)
	GetNodes(ctx context.Context) ([]Node, error)
	GetToken(ctx context.Context, token string) (OnboardingToken, error)
	GetValidToken(ctx context.Context, token string) (OnboardingToken, error)
	MarkNodeUnhealthy(ctx context.Context, id string) error
	MarkTokenUsed(ctx context.Context, token string) error
	UpdateHeartbeat(ctx context.Context, id string) error
	UpdateNodeIP(ctx context.Context, arg UpdateNodeIPParams) error
}

var _ Querier = (*Queries)(nil)
