// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package agentdb

import (
	"database/sql"
)

type Container struct {
	ID        string
	Image     string
	Name      string
	Port      int64
	Status    string
	DockerID  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
