// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package agentdb

import (
	"context"
	"database/sql"
)

const createContainer = `-- name: CreateContainer :exec
INSERT INTO containers (id, image, name, port, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateContainerParams struct {
	ID     string
	Image  string
	Name   string
	Port   int64
	Status string
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) error {
	_, err := q.db.ExecContext(ctx, createContainer,
		arg.ID,
		arg.Image,
		arg.Name,
		arg.Port,
		arg.Status,
	)
	return err
}

const getContainerByID = `-- name: GetContainerByID :one
SELECT id, image, name, port, status, docker_id, created_at, updated_at FROM containers WHERE id = ?
`

func (q *Queries) GetContainerByID(ctx context.Context, id string) (Container, error) {
	row := q.db.QueryRowContext(ctx, getContainerByID, id)
	var i Container
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.Name,
		&i.Port,
		&i.Status,
		&i.DockerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContainers = `-- name: GetContainers :many
SELECT id, image, name, port, status, docker_id, created_at, updated_at FROM containers
`

func (q *Queries) GetContainers(ctx context.Context) ([]Container, error) {
	rows, err := q.db.QueryContext(ctx, getContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ID,
			&i.Image,
			&i.Name,
			&i.Port,
			&i.Status,
			&i.DockerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContainerStatus = `-- name: UpdateContainerStatus :exec
UPDATE containers
SET status = ?, docker_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateContainerStatusParams struct {
	Status   string
	DockerID sql.NullString
	ID       string
}

func (q *Queries) UpdateContainerStatus(ctx context.Context, arg UpdateContainerStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateContainerStatus, arg.Status, arg.DockerID, arg.ID)
	return err
}
